name: climlab_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter-book
  - climlab
  - numpy
  - pip
  - pip:
    - cartopy
    - cdsapi
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - cdo
    - cartopy
    - metpy
    - netCDF4
